create table Groups(
    ID int IDENTITY (1,1) primary key not null ,
    NAME NVARCHAR(10) UNIQUE NOT NULL CHECK(len(NAME > 0)),
    RATING INT NOT NULL CHECK (RATING > -1 AND RATING < 6),
    YEAR INT NOT NULL CHECK (YEAR > 0 AND YEAR < 6),

)

CREATE TABLE DEPARTMENTS(
    ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY ,
    FINANCING MONEY NOT NULL CHECK(FINANCING > -1) DEFAULT 0,
    NAME NVARCHAR(100) NOT NULL CHECK (LEN(NAME) > 0) UNIQUE,

)

CREATE TABLE FACULTIES(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NAME NVARCHAR NOT NULL CHECK(LEN(NAME) > 0) UNIQUE
)

CREATE TABLE TEACHERS(
    ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    EMPLOYMENT_DATE DATE NOT NULL CHECK (EMPLOYMENT_DATE > '01.01.1990'),
    NAME NVARCHAR(MAX) NOT NULL CHECK(LEN(NAME) > 0),
    PREMIUM MONEY NOT NULL CHECK(PREMIUM > -1) DEFAULT 0,
    SALARY MONEY NOT NULL CHECK(SALARY > -1) DEFAULT 0,
    SURNAME NVARCHAR(MAX) NOT NULL CHECK(LEN(SURNAME) > 0)
)


SELECT * from Departments