CREATE TABLE DEPARTMENTS(
    ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    FINANCING MONEY NOT NULL CHECK (FINANCING >= 0) DEFAULT 0,
    NAME NVARCHAR(100) NOT NULL CHECK(LEN(NAME) > 0) UNIQUE
)

CREATE TABLE FACULTIES(
    ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    DEAN NVARCHAR(MAX) NOT NULL CHECK(LEN(DEAN) > 0),
    NAME NVARCHAR(100) NOT NULL CHECK(LEN(NAME) > 0) UNIQUE
)

CREATE TABLE GROUPS(
    ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL CHECK(LEN(NAME) > 0) UNIQUE,
    RATING INT NOT NULL CHECK(0<RATING<5),
    YEAR INT NOT NULL CHECK (1<=YEAR<=5)
)

CREATE TABLE TEACHERS(
    ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
    EMPLOYMENTDATE DATE NOT NULL CHECK (EMPLOYMENTDATE > 'O1.01.1990'),
    ISASSISTANT BIT NOT NULL DEFAULT 0,
    ISPROFESSOR BIT NOT NULL DEFAULT 0,
    NAME NVARCHAR(MAX) NOT NULL CHECK(LEN(NAME) > 0),
    POSITION NVARCHAR(MAX) NOT NULL CHECK(LEN(POSITION) > 0),
    PREMIUM MONEY NOT NULL CHECK (PREMIUM>=0) DEFAULT 0,
    SALARY MONEY NOT NULL CHECK (SALARY > 0),
    SURNAME NVARCHAR(MAX) NOT NULL CHECK (LEN(SURNAME) > 0)
)




SELECT NAME, FINANCING, ID 
FROM DEPARTMENTS;


SELECT NAME AS "Group Name", RATING AS "Group Rating"
FROM GROUPS;


SELECT SURNAME, 
       (SALARY / NULLIF(PREMIUM, 0)) * 100 AS "salary divided by premium in %",
       (SALARY / (SALARY + PREMIUM)) * 100 AS "salary divided by salary with premium in %"
FROM TEACHERS;


SELECT 'The dean of faculty ' + NAME + ' is ' + DEAN AS Faculty_Info
FROM FACULTIES;


SELECT SURNAME 
FROM TEACHERS 
WHERE ISPROFESSOR = 1 AND SALARY > 1050;


SELECT NAME 
FROM DEPARTMENTS 
WHERE FINANCING < 11000 OR FINANCING > 25000;


SELECT NAME 
FROM FACULTIES 
WHERE NAME != 'Computer Science';


SELECT SURNAME, POSITION 
FROM TEACHERS 
WHERE ISPROFESSOR = 0;


SELECT SURNAME, POSITION, SALARY, PREMIUM 
FROM TEACHERS 
WHERE ISASSISTANT = 1 AND PREMIUM BETWEEN 160 AND 550;


SELECT SURNAME, SALARY 
FROM TEACHERS 
WHERE ISASSISTANT = 1;


SELECT SURNAME, POSITION 
FROM TEACHERS 
WHERE EMPLOYMENTDATE < '2000-01-01';


SELECT NAME AS "Name of Department"
FROM DEPARTMENTS 
WHERE NAME < 'Software Development'
ORDER BY NAME;


SELECT SURNAME 
FROM TEACHERS 
WHERE ISASSISTANT = 1 AND (SALARY + PREMIUM) <= 1200;


SELECT NAME 
FROM GROUPS 
WHERE YEAR = 5 AND RATING BETWEEN 2 AND 4;


SELECT SURNAME 
FROM TEACHERS 
WHERE ISASSISTANT = 1 AND (SALARY < 550 OR PREMIUM < 200);


